name: very_good_slide_puzzle
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: 2.10.0

dependencies:
  bloc: ^8.0.1
  equatable: ^2.0.3
  fake_async: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.1
  gap: ^2.0.0
  google_fonts: ^2.1.0
  intl: ^0.17.0
  just_audio: ^0.9.20
  universal_platform: ^1.0.0+1
  url_launcher: ^6.0.17
  animated_styled_widget: 0.4.1
  responsive_property: ^0.0.6
  decorated_icon: ^1.2.1
  aligned_dialog: ^0.0.6
  aurora_decoration: 0.0.1

dev_dependencies:
  bloc_test: ^9.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0
  flutter_launcher_icons: "^0.9.2"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-Italic.ttf
          weight: 400
          style: italic

    - family: BalooThambi2
      fonts:
        - asset: assets/fonts/BalooThambi2-Regular.ttf
          weight: 400
        - asset: assets/fonts/BalooThambi2-Bold.ttf
          weight: 700
        - asset: assets/fonts/BalooThambi2-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/BalooThambi2-Medium.ttf
          weight: 500
        - asset: assets/fonts/BalooThambi2-SemiBold.ttf
          weight: 600

    - family: SF-Pro-Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700

    - family: Beon
      fonts:
        - asset: assets/fonts/Beon/Beon.otf
    - family: Night-Club-70s
      fonts:
        - asset: assets/fonts/Night-Club-70s/Night-Club-70s-Bold.ttf
          weight: 400
        - asset: assets/fonts/Night-Club-70s/Night-Club-70s-Regular.ttf
          weight: 700

    - family: Pacifico-Regular
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: DSZierschrift
      fonts:
        - asset: assets/fonts/DSZierschrift.ttf
    - family: Segoe UI
      fonts:
        - asset: assets/fonts/Segoe UI.ttf
          weight: 400
        - asset: assets/fonts/Segoe UI Bold.ttf
          weight: 700

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
